<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> deleting' => '<strong>Conferma</strong> cancellazione',
    'Are you sure you want to delete this item?' => 'Sei sicuro di volere cancellare questo articolo? ',
    'Back to overview' => 'Torna alla panoramica',
    'Calendar Extension' => 'Estensione del calendario',
    'Cancel' => 'Cancella',
    'Close' => 'Chiudi',
    'Create' => 'Crea',
    'Delete' => 'Rimouvi',
    'Edit' => 'Modifica',
    'End time must be after start time!' => 'L'ora di fine deve essere successiva all'ora di inizio! ',
    'Event' => 'Evento',
    'Extends the Calendar-Module to show external calendars with iCal' => 'Estende il modulo del calendario per mostrare calendari esterni via iCal',
    'External Calendar' => 'Calendario esterno',
    'External Calendar Entry' => 'Annotazione calendario esterno',
    'Manage external calendar for your profile.' => 'Gestisci il calendario esterno per il tuo profilo. ',
    'Manage external calendar here.' => 'Gestisci il calendario esterno qui.',
    'Save' => 'Salva',
    'Update' => 'Aggiorna',
    'View' => 'Vedi',
    'You are not allowed to show External Calendar!' => 'Non sei autorizzato a mostrare il calendario esterno!',
];
