<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Color' => 'Colore',
    'Daily synchronization' => 'Sincronizzazione giornaliera',
    'Event Mode' => 'Modalità evento',
    'Event Selection' => 'Scelta evento',
    'Hourly synchronization' => 'Sincronizzazione ogni ora',
    'ID' => 'ID',
    'No auto synchronization' => 'Nessuna sincronizzazione automatica',
    'Only sync events from current month' => 'Sincronizza solo eventi dal mese corrente',
    'Original Calendar Name' => 'Nome del calendario originale',
    'Original Calendar Scale' => 'Gamma del calendario originale',
    'Public' => 'Publiccare',
    'Sync Mode' => 'Modo di sincronizzazione',
    'Sync all events' => 'Sincronizza tutti eventi',
    'Timezone' => 'Fuso orario',
    'Title' => 'Titolo',
    'Url' => 'Url',
    'e.g. https://calendar.google.com/calendar/ical/...' => 'per esempio https://calendar.google.com/calendar/ical/...',
    'iCal Version' => 'Versione iCal',
];
