<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allows the user to edit/delete existing external calendar' => 'Consente all'utente di modificare/eliminare il calendario esterno esistente',
    'Allows the user to edit/delete existing external calendar entries' => 'Consente all'utente di modificare/eliminare registri su calendario esterne esistenti',
    'Manage external Calendar' => 'Gestire calendario esterno',
    'Manage external entries' => 'Gestire registri esterni',
    'You are not allowed to manage External Calendar!' => 'Non sei autorizzato a gestire il calendario esterno!',
    'You need to be member of the space "%space_name%" to access this calendar!' => 'Devi essere membro dello spazio "%space_name%" per accedere a questo calendario!',
];
