<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Azioni',
    'Add Calendar' => 'Aggiungere calendario',
    'Add external Calendar' => 'Aggiungere calendario esterno',
    'Calendar' => 'Calendario',
    'Calendar: {modelClass}' => 'Calendario: {modelClass}',
    'External Calendars' => 'Calendari esterni',
    'Private' => 'Privato',
    'Public' => 'Pubblico',
    'Sync Calendar' => 'Sincronizza calendario',
    'Title and Color' => 'Titolo e colore',
    'Update {modelClass}: ' => 'Aggiorna {modelClass}: ',
];
