<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create' => 'Anlegen',
    'End time must be after start time!' => 'Das Ende muss nach dem Start liegen!',
    'External Calendar Entry' => 'Externer Kalendereintrag',
    'You are not allowed to show External Calendar!' => 'Sie haben keine Berechtigung, externe Kalender zu sehen!',
    '<strong>Confirm</strong> deleting' => 'Löschen <strong>bestätigen</strong>',
    'Are you sure you want to delete this item?' => 'Wollen Sie diesen Eintrag wirklich löschen?',
    'Back to overview' => 'Zurück zur Übersicht',
    'Calendar Extension' => 'Kalender-Erweiterung',
    'Cancel' => 'Abbrechen',
    'Close' => 'Schließen',
    'Delete' => 'Löschen',
    'Edit' => 'Bearbeiten',
    'Event' => 'Termin',
    'Extends the Calendar-Module to show external calendars with iCal' => 'Erweitert das Kalender-Modul, um externe Kalender im iCal-Format zu integrieren.',
    'External Calendar' => 'Externer Kalender',
    'Manage external calendar for your profile.' => 'Verwalte hier externe Kalender für dein Profil.',
    'Manage external calendar here.' => 'Verwalte hier deine externen Kalender.',
    'Save' => 'Speichern',
    'Update' => 'Bearbeiten',
    'View' => 'Anzeigen',
];
