<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Event Mode' => '',
    'Color' => 'Farbe',
    'Daily synchronization' => 'Tägliche Synchronisation',
    'Event Selection' => 'Event-Auswahl',
    'Hourly synchronization' => 'Stündliche Synchronisation',
    'ID' => 'ID',
    'No auto synchronization' => 'Keine automatische Synchronisation',
    'Only sync events from current month' => 'Nur Termine aus dem aktuellen Monat synchronisieren',
    'Original Calendar Name' => 'Originaler Kalendername',
    'Original Calendar Scale' => 'Originale Kalenderskala',
    'Public' => 'Öffentlich',
    'Sync Mode' => 'Synchronisationsmethode',
    'Sync all events' => 'Alle Termine synchronisieren',
    'Timezone' => 'Zeitzone',
    'Title' => 'Titel',
    'Url' => 'Url',
    'e.g. https://calendar.google.com/calendar/ical/...' => 'z.B. https://calendar.google.com/calendar/ical/...',
    'iCal Version' => 'iCal Version',
];
