<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
    'Allows the user to edit/delete existing external calendar entries' => 'Erlaube Nutzern bestehende externe Kalendereinträge zu bearbeiten/löschen.',
    'Manage external entries' => 'Verwalte externe Kalendereinträge',
    'Manage external Calendar' => 'Verwalte externe Kalender',
    'Allows the user to edit/delete existing external calendar' => 'Erlaube Nutzern bestehende externe Kalender zu bearbeiten/löschen.',
    'You are not allowed to manage External Calendar!' => 'Sie haben keine Rechte, um externe Kalender zu verwalten!',
    'You need to be member of the space "%space_name%" to access this calendar!' => 'Sie müssen Mitglied im Space "%space_name%" sein, um diesen Kalender sehen zu können!'
);
